# Generated by Django 5.2.6 on 2025-11-03 13:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('prefix', models.CharField(default='AS', max_length=10, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='asset_type_images/')),
            ],
        ),
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_type', models.CharField(choices=[('BULK', 'Quick Bulk Sale'), ('MIXED', 'Mixed Item Sale'), ('SINGLE', 'Single Asset Sale')], default='MIXED', max_length=10)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('total_sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_purchase_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Sale Record',
                'verbose_name_plural': 'Sale Records',
            },
        ),
        migrations.CreateModel(
            name='HardwareAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('location', models.CharField(choices=[('GITHURAI_45', 'Githurai 45'), ('KIRIGITI', 'Kirigiti'), ('KIAMBU', 'Kiambu')], default='KIRIGITI', max_length=20)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('PENDING_SALE', 'Pending Sale'), ('SOLD', 'Sold'), ('SCRAPPED', 'Scrapped')], default='IN_STOCK', max_length=20)),
                ('warranty_end_date', models.DateField(blank=True, null=True)),
                ('individual_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.assettype')),
                ('sale_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_assets', to='inventory.salerecord')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('log_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.hardwareasset')),
            ],
        ),
    ]
