# Generated by Django 5.2.6 on 2025-09-30 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('warranty_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('PENDING_SALE', 'Pending Sale'), ('SOLD', 'Sold'), ('SCRAPPED', 'Scrapped')], default='IN_STOCK', max_length=20)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Asset Types',
            },
        ),
        migrations.CreateModel(
            name='AssetRetirementSale',
            fields=[
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sale_record', serialize=False, to='inventory.hardwareasset')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retirement_date', models.DateField(auto_now_add=True)),
                ('cost_basis', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('profit_loss', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='hardwareasset',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.assettype'),
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('log_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.hardwareasset')),
            ],
        ),
    ]
