# Generated by Django 5.2.6 on 2025-11-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MixedSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_purchase_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mixed Asset Sale',
                'verbose_name_plural': 'Mixed Asset Sales',
            },
        ),
    ]
