# Generated by Django 5.2.6 on 2025-10-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_hardwareasset_pending_sale_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwareasset',
            name='location',
            field=models.CharField(choices=[('GITHURAI_45', 'Githurai 45'), ('KIRIGITI', 'Kirigiti'), ('KIAMBU', 'Kiambu')], default='KIRIGITI', max_length=20),
        ),
    ]
