# Generated by Django 5.2.6 on 2025-11-14 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_mixedsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwareasset',
            name='mixed_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mixed_sale_assets', to='inventory.mixedsale'),
        ),
    ]
