# Generated by Django 5.2.6 on 2025-10-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_hardwareasset_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assettype',
            options={},
        ),
        migrations.AddField(
            model_name='assettype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='asset_type_images/'),
        ),
    ]
